extern alias Worker;
global using Stripe;
global using Shouldly;
global using System.Net;
global using AutoFixture;
global using NSubstitute;
global using Stripe.Checkout;
global using WatchStore.Data;
global using System.Text.Json;
global using WatchStore.Shared;
global using System.Data.Common;
global using Azure.Storage.Blobs;
global using System.Net.Http.Json;
global using System.Globalization;
global using WatchStore.Data.Models;
global using Testcontainers.Azurite;
global using System.Security.Claims;
global using System.Net.Http.Headers;
global using Microsoft.AspNetCore.Mvc;
global using Testcontainers.PostgreSql;
global using System.Text.Encodings.Web;
global using Testcontainers.ServiceBus;
global using WatchStore.Api.Common.Auth;
global using Azure.Messaging.ServiceBus;
global using WatchStore.Contracts.Orders;
global using Microsoft.Extensions.Hosting;
global using WatchStore.Api.Common.Stripe;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.TestHost;
global using WatchStore.Api.Features.Orders;
global using WatchStore.Api.Features.Watches;
global using WatchStore.Api.Features.Baskets;
global using WatchStore.Api.Common.Messaging;
global using WatchStore.IntegrationTests.Data;
global using DotNet.Testcontainers.Containers;
global using WatchStore.Api.Features.Payments;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.Configuration;
global using Microsoft.AspNetCore.Authentication;
global using WatchStore.IntegrationTests.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using WatchStore.Api.Features.Watches.AddWatch;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.Logging.Abstractions;
global using WatchStore.IntegrationTests.Authentication;
global using WatchStore.Api.Features.Payments.Constants;
global using WatchStore.Api.Features.Watches.UpdateWatch;
global using GetOrder = WatchStore.Api.Features.Orders.GetOrder;
global using GetWatch = WatchStore.Api.Features.Watches.GetWatch;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using GetOrders = WatchStore.Api.Features.Orders.GetOrders;
global using GetBasket = WatchStore.Api.Features.Baskets.GetBasket;
global using WatchStore.Api.Features.Payments.CreateCheckoutSession;
global using GetWatches = WatchStore.Api.Features.Watches.GetWatches;
global using UpsertBasket = WatchStore.Api.Features.Baskets.UpsertBasket;
global using WorkerHostFactory = Worker::WatchStore.Worker.WorkerHostFactory;